# Generated by Django 3.1.7 on 2021-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('purchage_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('fine_amt', models.IntegerField()),
                ('violation_done', models.CharField(max_length=500)),
                ('violation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
